[package]
name = "retro-video-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_6"] }
glib = "0.20"
tokio = { version = "1.35", features = ["full"] }
rfd = "0.13"
tempfile = "3.8"
anyhow = "1.0"
